// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: feed_service.proto

package feedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeedRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Limit               int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeTimestampUnix *int64                 `protobuf:"varint,2,opt,name=before_timestamp_unix,json=beforeTimestampUnix,proto3,oneof" json:"before_timestamp_unix,omitempty"` // cursor
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_feed_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFeedRequest) GetBeforeTimestampUnix() int64 {
	if x != nil && x.BeforeTimestampUnix != nil {
		return *x.BeforeTimestampUnix
	}
	return 0
}

type FeedItemMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModuleType    string                 `protobuf:"bytes,2,opt,name=module_type,json=moduleType,proto3" json:"module_type,omitempty"`
	SourceId      uint32                 `protobuf:"varint,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,8,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	UrlPath       string                 `protobuf:"bytes,9,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItemMsg) Reset() {
	*x = FeedItemMsg{}
	mi := &file_feed_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItemMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItemMsg) ProtoMessage() {}

func (x *FeedItemMsg) ProtoReflect() protoreflect.Message {
	mi := &file_feed_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItemMsg.ProtoReflect.Descriptor instead.
func (*FeedItemMsg) Descriptor() ([]byte, []int) {
	return file_feed_service_proto_rawDescGZIP(), []int{1}
}

func (x *FeedItemMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedItemMsg) GetModuleType() string {
	if x != nil {
		return x.ModuleType
	}
	return ""
}

func (x *FeedItemMsg) GetSourceId() uint32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *FeedItemMsg) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItemMsg) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *FeedItemMsg) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *FeedItemMsg) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *FeedItemMsg) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *FeedItemMsg) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

type GetFeedResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Items                   []*FeedItemMsg         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextBeforeTimestampUnix *int64                 `protobuf:"varint,2,opt,name=next_before_timestamp_unix,json=nextBeforeTimestampUnix,proto3,oneof" json:"next_before_timestamp_unix,omitempty"`
	Error                   *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetFeedResponse) Reset() {
	*x = GetFeedResponse{}
	mi := &file_feed_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse) ProtoMessage() {}

func (x *GetFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return file_feed_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeedResponse) GetItems() []*FeedItemMsg {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetFeedResponse) GetNextBeforeTimestampUnix() int64 {
	if x != nil && x.NextBeforeTimestampUnix != nil {
		return *x.NextBeforeTimestampUnix
	}
	return 0
}

func (x *GetFeedResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_feed_service_proto protoreflect.FileDescriptor

const file_feed_service_proto_rawDesc = "" +
	"\n" +
	"\x12feed_service.proto\x12\afeed.v1\"y\n" +
	"\x0eGetFeedRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x127\n" +
	"\x15before_timestamp_unix\x18\x02 \x01(\x03H\x00R\x13beforeTimestampUnix\x88\x01\x01B\x18\n" +
	"\x16_before_timestamp_unix\"\x92\x02\n" +
	"\vFeedItemMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmodule_type\x18\x02 \x01(\tR\n" +
	"moduleType\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\rR\bsourceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\b \x01(\x03R\fcommentCount\x12\x19\n" +
	"\burl_path\x18\t \x01(\tR\aurlPath\"\xc3\x01\n" +
	"\x0fGetFeedResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.feed.v1.FeedItemMsgR\x05items\x12@\n" +
	"\x1anext_before_timestamp_unix\x18\x02 \x01(\x03H\x00R\x17nextBeforeTimestampUnix\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x01R\x05error\x88\x01\x01B\x1d\n" +
	"\x1b_next_before_timestamp_unixB\b\n" +
	"\x06_errorB5Z3github.com/your-moon/grape-backend/api/proto/feedv1b\x06proto3"

var (
	file_feed_service_proto_rawDescOnce sync.Once
	file_feed_service_proto_rawDescData []byte
)

func file_feed_service_proto_rawDescGZIP() []byte {
	file_feed_service_proto_rawDescOnce.Do(func() {
		file_feed_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_service_proto_rawDesc), len(file_feed_service_proto_rawDesc)))
	})
	return file_feed_service_proto_rawDescData
}

var file_feed_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_feed_service_proto_goTypes = []any{
	(*GetFeedRequest)(nil),  // 0: feed.v1.GetFeedRequest
	(*FeedItemMsg)(nil),     // 1: feed.v1.FeedItemMsg
	(*GetFeedResponse)(nil), // 2: feed.v1.GetFeedResponse
}
var file_feed_service_proto_depIdxs = []int32{
	1, // 0: feed.v1.GetFeedResponse.items:type_name -> feed.v1.FeedItemMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feed_service_proto_init() }
func file_feed_service_proto_init() {
	if File_feed_service_proto != nil {
		return
	}
	file_feed_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_feed_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_service_proto_rawDesc), len(file_feed_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feed_service_proto_goTypes,
		DependencyIndexes: file_feed_service_proto_depIdxs,
		MessageInfos:      file_feed_service_proto_msgTypes,
	}.Build()
	File_feed_service_proto = out.File
	file_feed_service_proto_goTypes = nil
	file_feed_service_proto_depIdxs = nil
}
