// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: engagement_service.proto

package engagementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TargetType for likes/comments: product, job, market, review
type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED TargetType = 0
	TargetType_TARGET_TYPE_PRODUCT     TargetType = 1
	TargetType_TARGET_TYPE_JOB         TargetType = 2
	TargetType_TARGET_TYPE_MARKET      TargetType = 3
	TargetType_TARGET_TYPE_REVIEW      TargetType = 4
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "TARGET_TYPE_PRODUCT",
		2: "TARGET_TYPE_JOB",
		3: "TARGET_TYPE_MARKET",
		4: "TARGET_TYPE_REVIEW",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"TARGET_TYPE_PRODUCT":     1,
		"TARGET_TYPE_JOB":         2,
		"TARGET_TYPE_MARKET":      3,
		"TARGET_TYPE_REVIEW":      4,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_engagement_service_proto_enumTypes[0].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_engagement_service_proto_enumTypes[0]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{0}
}

type ToggleLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    TargetType             `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=engagement.v1.TargetType" json:"target_type,omitempty"`
	TargetId      uint32                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeRequest) Reset() {
	*x = ToggleLikeRequest{}
	mi := &file_engagement_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeRequest) ProtoMessage() {}

func (x *ToggleLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engagement_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeRequest.ProtoReflect.Descriptor instead.
func (*ToggleLikeRequest) Descriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{0}
}

func (x *ToggleLikeRequest) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *ToggleLikeRequest) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ToggleLikeRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ToggleLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"` // true if now liked, false if now unliked
	LikeCount     int64                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeResponse) Reset() {
	*x = ToggleLikeResponse{}
	mi := &file_engagement_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeResponse) ProtoMessage() {}

func (x *ToggleLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engagement_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeResponse.ProtoReflect.Descriptor instead.
func (*ToggleLikeResponse) Descriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{1}
}

func (x *ToggleLikeResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *ToggleLikeResponse) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type GetLikeCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    TargetType             `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=engagement.v1.TargetType" json:"target_type,omitempty"`
	TargetId      uint32                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeCountRequest) Reset() {
	*x = GetLikeCountRequest{}
	mi := &file_engagement_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCountRequest) ProtoMessage() {}

func (x *GetLikeCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engagement_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCountRequest.ProtoReflect.Descriptor instead.
func (*GetLikeCountRequest) Descriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLikeCountRequest) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *GetLikeCountRequest) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type GetLikeCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeCountResponse) Reset() {
	*x = GetLikeCountResponse{}
	mi := &file_engagement_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCountResponse) ProtoMessage() {}

func (x *GetLikeCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engagement_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCountResponse.ProtoReflect.Descriptor instead.
func (*GetLikeCountResponse) Descriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLikeCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type IsLikedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    TargetType             `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=engagement.v1.TargetType" json:"target_type,omitempty"`
	TargetId      uint32                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikedRequest) Reset() {
	*x = IsLikedRequest{}
	mi := &file_engagement_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikedRequest) ProtoMessage() {}

func (x *IsLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engagement_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikedRequest.ProtoReflect.Descriptor instead.
func (*IsLikedRequest) Descriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{4}
}

func (x *IsLikedRequest) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *IsLikedRequest) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *IsLikedRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsLikedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikedResponse) Reset() {
	*x = IsLikedResponse{}
	mi := &file_engagement_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikedResponse) ProtoMessage() {}

func (x *IsLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engagement_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikedResponse.ProtoReflect.Descriptor instead.
func (*IsLikedResponse) Descriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{5}
}

func (x *IsLikedResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type GetLikeCountsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    TargetType             `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=engagement.v1.TargetType" json:"target_type,omitempty"`
	TargetIds     []uint32               `protobuf:"varint,2,rep,packed,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	UserId        *uint32                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"` // if set, response includes is_liked per id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeCountsBatchRequest) Reset() {
	*x = GetLikeCountsBatchRequest{}
	mi := &file_engagement_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeCountsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCountsBatchRequest) ProtoMessage() {}

func (x *GetLikeCountsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engagement_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCountsBatchRequest.ProtoReflect.Descriptor instead.
func (*GetLikeCountsBatchRequest) Descriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetLikeCountsBatchRequest) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *GetLikeCountsBatchRequest) GetTargetIds() []uint32 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *GetLikeCountsBatchRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

type LikeCountItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint32                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	IsLiked       bool                   `protobuf:"varint,3,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCountItem) Reset() {
	*x = LikeCountItem{}
	mi := &file_engagement_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCountItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCountItem) ProtoMessage() {}

func (x *LikeCountItem) ProtoReflect() protoreflect.Message {
	mi := &file_engagement_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCountItem.ProtoReflect.Descriptor instead.
func (*LikeCountItem) Descriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{7}
}

func (x *LikeCountItem) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *LikeCountItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LikeCountItem) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type GetLikeCountsBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LikeCountItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeCountsBatchResponse) Reset() {
	*x = GetLikeCountsBatchResponse{}
	mi := &file_engagement_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeCountsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCountsBatchResponse) ProtoMessage() {}

func (x *GetLikeCountsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engagement_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCountsBatchResponse.ProtoReflect.Descriptor instead.
func (*GetLikeCountsBatchResponse) Descriptor() ([]byte, []int) {
	return file_engagement_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetLikeCountsBatchResponse) GetItems() []*LikeCountItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_engagement_service_proto protoreflect.FileDescriptor

const file_engagement_service_proto_rawDesc = "" +
	"\n" +
	"\x18engagement_service.proto\x12\rengagement.v1\"\x85\x01\n" +
	"\x11ToggleLikeRequest\x12:\n" +
	"\vtarget_type\x18\x01 \x01(\x0e2\x19.engagement.v1.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\rR\btargetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"I\n" +
	"\x12ToggleLikeResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03R\tlikeCount\"n\n" +
	"\x13GetLikeCountRequest\x12:\n" +
	"\vtarget_type\x18\x01 \x01(\x0e2\x19.engagement.v1.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\rR\btargetId\",\n" +
	"\x14GetLikeCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x82\x01\n" +
	"\x0eIsLikedRequest\x12:\n" +
	"\vtarget_type\x18\x01 \x01(\x0e2\x19.engagement.v1.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\rR\btargetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"'\n" +
	"\x0fIsLikedResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\"\xa0\x01\n" +
	"\x19GetLikeCountsBatchRequest\x12:\n" +
	"\vtarget_type\x18\x01 \x01(\x0e2\x19.engagement.v1.TargetTypeR\n" +
	"targetType\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x02 \x03(\rR\ttargetIds\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\rH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"]\n" +
	"\rLikeCountItem\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\rR\btargetId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x19\n" +
	"\bis_liked\x18\x03 \x01(\bR\aisLiked\"P\n" +
	"\x1aGetLikeCountsBatchResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.engagement.v1.LikeCountItemR\x05items*\x87\x01\n" +
	"\n" +
	"TargetType\x12\x1b\n" +
	"\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TARGET_TYPE_PRODUCT\x10\x01\x12\x13\n" +
	"\x0fTARGET_TYPE_JOB\x10\x02\x12\x16\n" +
	"\x12TARGET_TYPE_MARKET\x10\x03\x12\x16\n" +
	"\x12TARGET_TYPE_REVIEW\x10\x04B;Z9github.com/your-moon/grape-backend/api/proto/engagementv1b\x06proto3"

var (
	file_engagement_service_proto_rawDescOnce sync.Once
	file_engagement_service_proto_rawDescData []byte
)

func file_engagement_service_proto_rawDescGZIP() []byte {
	file_engagement_service_proto_rawDescOnce.Do(func() {
		file_engagement_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engagement_service_proto_rawDesc), len(file_engagement_service_proto_rawDesc)))
	})
	return file_engagement_service_proto_rawDescData
}

var file_engagement_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_engagement_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_engagement_service_proto_goTypes = []any{
	(TargetType)(0),                    // 0: engagement.v1.TargetType
	(*ToggleLikeRequest)(nil),          // 1: engagement.v1.ToggleLikeRequest
	(*ToggleLikeResponse)(nil),         // 2: engagement.v1.ToggleLikeResponse
	(*GetLikeCountRequest)(nil),        // 3: engagement.v1.GetLikeCountRequest
	(*GetLikeCountResponse)(nil),       // 4: engagement.v1.GetLikeCountResponse
	(*IsLikedRequest)(nil),             // 5: engagement.v1.IsLikedRequest
	(*IsLikedResponse)(nil),            // 6: engagement.v1.IsLikedResponse
	(*GetLikeCountsBatchRequest)(nil),  // 7: engagement.v1.GetLikeCountsBatchRequest
	(*LikeCountItem)(nil),              // 8: engagement.v1.LikeCountItem
	(*GetLikeCountsBatchResponse)(nil), // 9: engagement.v1.GetLikeCountsBatchResponse
}
var file_engagement_service_proto_depIdxs = []int32{
	0, // 0: engagement.v1.ToggleLikeRequest.target_type:type_name -> engagement.v1.TargetType
	0, // 1: engagement.v1.GetLikeCountRequest.target_type:type_name -> engagement.v1.TargetType
	0, // 2: engagement.v1.IsLikedRequest.target_type:type_name -> engagement.v1.TargetType
	0, // 3: engagement.v1.GetLikeCountsBatchRequest.target_type:type_name -> engagement.v1.TargetType
	8, // 4: engagement.v1.GetLikeCountsBatchResponse.items:type_name -> engagement.v1.LikeCountItem
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_engagement_service_proto_init() }
func file_engagement_service_proto_init() {
	if File_engagement_service_proto != nil {
		return
	}
	file_engagement_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engagement_service_proto_rawDesc), len(file_engagement_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engagement_service_proto_goTypes,
		DependencyIndexes: file_engagement_service_proto_depIdxs,
		EnumInfos:         file_engagement_service_proto_enumTypes,
		MessageInfos:      file_engagement_service_proto_msgTypes,
	}.Build()
	File_engagement_service_proto = out.File
	file_engagement_service_proto_goTypes = nil
	file_engagement_service_proto_depIdxs = nil
}
