// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: market_service.proto

package marketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentUserId *uint32                `protobuf:"varint,2,opt,name=current_user_id,json=currentUserId,proto3,oneof" json:"current_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketRequest) Reset() {
	*x = GetMarketRequest{}
	mi := &file_market_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketRequest) ProtoMessage() {}

func (x *GetMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketRequest.ProtoReflect.Descriptor instead.
func (*GetMarketRequest) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMarketRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMarketRequest) GetCurrentUserId() uint32 {
	if x != nil && x.CurrentUserId != nil {
		return *x.CurrentUserId
	}
	return 0
}

type GetMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketJson    []byte                 `protobuf:"bytes,1,opt,name=market_json,json=marketJson,proto3" json:"market_json,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketResponse) Reset() {
	*x = GetMarketResponse{}
	mi := &file_market_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketResponse) ProtoMessage() {}

func (x *GetMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketResponse.ProtoReflect.Descriptor instead.
func (*GetMarketResponse) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMarketResponse) GetMarketJson() []byte {
	if x != nil {
		return x.MarketJson
	}
	return nil
}

func (x *GetMarketResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ListMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	CurrentUserId *uint32                `protobuf:"varint,3,opt,name=current_user_id,json=currentUserId,proto3,oneof" json:"current_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsRequest) Reset() {
	*x = ListMarketsRequest{}
	mi := &file_market_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsRequest) ProtoMessage() {}

func (x *ListMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsRequest.ProtoReflect.Descriptor instead.
func (*ListMarketsRequest) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListMarketsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMarketsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMarketsRequest) GetCurrentUserId() uint32 {
	if x != nil && x.CurrentUserId != nil {
		return *x.CurrentUserId
	}
	return 0
}

type ListMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemsJson     []byte                 `protobuf:"bytes,1,opt,name=items_json,json=itemsJson,proto3" json:"items_json,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsResponse) Reset() {
	*x = ListMarketsResponse{}
	mi := &file_market_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsResponse) ProtoMessage() {}

func (x *ListMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsResponse.ProtoReflect.Descriptor instead.
func (*ListMarketsResponse) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListMarketsResponse) GetItemsJson() []byte {
	if x != nil {
		return x.ItemsJson
	}
	return nil
}

func (x *ListMarketsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMarketsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type CreateMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadJson   []byte                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMarketRequest) Reset() {
	*x = CreateMarketRequest{}
	mi := &file_market_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarketRequest) ProtoMessage() {}

func (x *CreateMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarketRequest.ProtoReflect.Descriptor instead.
func (*CreateMarketRequest) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMarketRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *CreateMarketRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketJson    []byte                 `protobuf:"bytes,1,opt,name=market_json,json=marketJson,proto3" json:"market_json,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMarketResponse) Reset() {
	*x = CreateMarketResponse{}
	mi := &file_market_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarketResponse) ProtoMessage() {}

func (x *CreateMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarketResponse.ProtoReflect.Descriptor instead.
func (*CreateMarketResponse) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMarketResponse) GetMarketJson() []byte {
	if x != nil {
		return x.MarketJson
	}
	return nil
}

func (x *CreateMarketResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type UpdateMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMarketRequest) Reset() {
	*x = UpdateMarketRequest{}
	mi := &file_market_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMarketRequest) ProtoMessage() {}

func (x *UpdateMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMarketRequest.ProtoReflect.Descriptor instead.
func (*UpdateMarketRequest) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMarketRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMarketRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type UpdateMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketJson    []byte                 `protobuf:"bytes,1,opt,name=market_json,json=marketJson,proto3" json:"market_json,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMarketResponse) Reset() {
	*x = UpdateMarketResponse{}
	mi := &file_market_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMarketResponse) ProtoMessage() {}

func (x *UpdateMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMarketResponse.ProtoReflect.Descriptor instead.
func (*UpdateMarketResponse) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMarketResponse) GetMarketJson() []byte {
	if x != nil {
		return x.MarketJson
	}
	return nil
}

func (x *UpdateMarketResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DeleteMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMarketRequest) Reset() {
	*x = DeleteMarketRequest{}
	mi := &file_market_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMarketRequest) ProtoMessage() {}

func (x *DeleteMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMarketRequest.ProtoReflect.Descriptor instead.
func (*DeleteMarketRequest) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMarketRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMarketResponse) Reset() {
	*x = DeleteMarketResponse{}
	mi := &file_market_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMarketResponse) ProtoMessage() {}

func (x *DeleteMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMarketResponse.ProtoReflect.Descriptor instead.
func (*DeleteMarketResponse) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMarketResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type RecordViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      uint32                 `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId        *uint32                `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	IpAddress     *string                `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3,oneof" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordViewRequest) Reset() {
	*x = RecordViewRequest{}
	mi := &file_market_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewRequest) ProtoMessage() {}

func (x *RecordViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewRequest.ProtoReflect.Descriptor instead.
func (*RecordViewRequest) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{10}
}

func (x *RecordViewRequest) GetMarketId() uint32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *RecordViewRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *RecordViewRequest) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

type RecordViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordViewResponse) Reset() {
	*x = RecordViewResponse{}
	mi := &file_market_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewResponse) ProtoMessage() {}

func (x *RecordViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewResponse.ProtoReflect.Descriptor instead.
func (*RecordViewResponse) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{11}
}

type ListFeedItemsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Limit               int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeTimestampUnix *int64                 `protobuf:"varint,2,opt,name=before_timestamp_unix,json=beforeTimestampUnix,proto3,oneof" json:"before_timestamp_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListFeedItemsRequest) Reset() {
	*x = ListFeedItemsRequest{}
	mi := &file_market_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsRequest) ProtoMessage() {}

func (x *ListFeedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedItemsRequest) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListFeedItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFeedItemsRequest) GetBeforeTimestampUnix() int64 {
	if x != nil && x.BeforeTimestampUnix != nil {
		return *x.BeforeTimestampUnix
	}
	return 0
}

type FeedItemMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModuleType    string                 `protobuf:"bytes,2,opt,name=module_type,json=moduleType,proto3" json:"module_type,omitempty"`
	SourceId      uint32                 `protobuf:"varint,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,8,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	UrlPath       string                 `protobuf:"bytes,9,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItemMsg) Reset() {
	*x = FeedItemMsg{}
	mi := &file_market_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItemMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItemMsg) ProtoMessage() {}

func (x *FeedItemMsg) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItemMsg.ProtoReflect.Descriptor instead.
func (*FeedItemMsg) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{13}
}

func (x *FeedItemMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedItemMsg) GetModuleType() string {
	if x != nil {
		return x.ModuleType
	}
	return ""
}

func (x *FeedItemMsg) GetSourceId() uint32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *FeedItemMsg) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItemMsg) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *FeedItemMsg) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *FeedItemMsg) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *FeedItemMsg) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *FeedItemMsg) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

type ListFeedItemsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Items                   []*FeedItemMsg         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextBeforeTimestampUnix *int64                 `protobuf:"varint,2,opt,name=next_before_timestamp_unix,json=nextBeforeTimestampUnix,proto3,oneof" json:"next_before_timestamp_unix,omitempty"`
	Error                   *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListFeedItemsResponse) Reset() {
	*x = ListFeedItemsResponse{}
	mi := &file_market_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsResponse) ProtoMessage() {}

func (x *ListFeedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedItemsResponse) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListFeedItemsResponse) GetItems() []*FeedItemMsg {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFeedItemsResponse) GetNextBeforeTimestampUnix() int64 {
	if x != nil && x.NextBeforeTimestampUnix != nil {
		return *x.NextBeforeTimestampUnix
	}
	return 0
}

func (x *ListFeedItemsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_market_service_proto protoreflect.FileDescriptor

const file_market_service_proto_rawDesc = "" +
	"\n" +
	"\x14market_service.proto\x12\tmarket.v1\"c\n" +
	"\x10GetMarketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12+\n" +
	"\x0fcurrent_user_id\x18\x02 \x01(\rH\x00R\rcurrentUserId\x88\x01\x01B\x12\n" +
	"\x10_current_user_id\"Y\n" +
	"\x11GetMarketResponse\x12\x1f\n" +
	"\vmarket_json\x18\x01 \x01(\fR\n" +
	"marketJson\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x7f\n" +
	"\x12ListMarketsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12+\n" +
	"\x0fcurrent_user_id\x18\x03 \x01(\rH\x00R\rcurrentUserId\x88\x01\x01B\x12\n" +
	"\x10_current_user_id\"o\n" +
	"\x13ListMarketsResponse\x12\x1d\n" +
	"\n" +
	"items_json\x18\x01 \x01(\fR\titemsJson\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"Q\n" +
	"\x13CreateMarketRequest\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\fR\vpayloadJson\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"\\\n" +
	"\x14CreateMarketResponse\x12\x1f\n" +
	"\vmarket_json\x18\x01 \x01(\fR\n" +
	"marketJson\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"H\n" +
	"\x13UpdateMarketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\"\\\n" +
	"\x14UpdateMarketResponse\x12\x1f\n" +
	"\vmarket_json\x18\x01 \x01(\fR\n" +
	"marketJson\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"%\n" +
	"\x13DeleteMarketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\";\n" +
	"\x14DeleteMarketResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x8d\x01\n" +
	"\x11RecordViewRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\rR\bmarketId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\rH\x00R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tH\x01R\tipAddress\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_ip_address\"\x14\n" +
	"\x12RecordViewResponse\"\x7f\n" +
	"\x14ListFeedItemsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x127\n" +
	"\x15before_timestamp_unix\x18\x02 \x01(\x03H\x00R\x13beforeTimestampUnix\x88\x01\x01B\x18\n" +
	"\x16_before_timestamp_unix\"\x92\x02\n" +
	"\vFeedItemMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmodule_type\x18\x02 \x01(\tR\n" +
	"moduleType\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\rR\bsourceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\b \x01(\x03R\fcommentCount\x12\x19\n" +
	"\burl_path\x18\t \x01(\tR\aurlPath\"\xcb\x01\n" +
	"\x15ListFeedItemsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.market.v1.FeedItemMsgR\x05items\x12@\n" +
	"\x1anext_before_timestamp_unix\x18\x02 \x01(\x03H\x00R\x17nextBeforeTimestampUnix\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x01R\x05error\x88\x01\x01B\x1d\n" +
	"\x1b_next_before_timestamp_unixB\b\n" +
	"\x06_errorB7Z5github.com/your-moon/grape-backend/api/proto/marketv1b\x06proto3"

var (
	file_market_service_proto_rawDescOnce sync.Once
	file_market_service_proto_rawDescData []byte
)

func file_market_service_proto_rawDescGZIP() []byte {
	file_market_service_proto_rawDescOnce.Do(func() {
		file_market_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_service_proto_rawDesc), len(file_market_service_proto_rawDesc)))
	})
	return file_market_service_proto_rawDescData
}

var file_market_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_market_service_proto_goTypes = []any{
	(*GetMarketRequest)(nil),      // 0: market.v1.GetMarketRequest
	(*GetMarketResponse)(nil),     // 1: market.v1.GetMarketResponse
	(*ListMarketsRequest)(nil),    // 2: market.v1.ListMarketsRequest
	(*ListMarketsResponse)(nil),   // 3: market.v1.ListMarketsResponse
	(*CreateMarketRequest)(nil),   // 4: market.v1.CreateMarketRequest
	(*CreateMarketResponse)(nil),  // 5: market.v1.CreateMarketResponse
	(*UpdateMarketRequest)(nil),   // 6: market.v1.UpdateMarketRequest
	(*UpdateMarketResponse)(nil),  // 7: market.v1.UpdateMarketResponse
	(*DeleteMarketRequest)(nil),   // 8: market.v1.DeleteMarketRequest
	(*DeleteMarketResponse)(nil),  // 9: market.v1.DeleteMarketResponse
	(*RecordViewRequest)(nil),     // 10: market.v1.RecordViewRequest
	(*RecordViewResponse)(nil),    // 11: market.v1.RecordViewResponse
	(*ListFeedItemsRequest)(nil),  // 12: market.v1.ListFeedItemsRequest
	(*FeedItemMsg)(nil),           // 13: market.v1.FeedItemMsg
	(*ListFeedItemsResponse)(nil), // 14: market.v1.ListFeedItemsResponse
}
var file_market_service_proto_depIdxs = []int32{
	13, // 0: market.v1.ListFeedItemsResponse.items:type_name -> market.v1.FeedItemMsg
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_market_service_proto_init() }
func file_market_service_proto_init() {
	if File_market_service_proto != nil {
		return
	}
	file_market_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_service_proto_rawDesc), len(file_market_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_service_proto_goTypes,
		DependencyIndexes: file_market_service_proto_depIdxs,
		MessageInfos:      file_market_service_proto_msgTypes,
	}.Build()
	File_market_service_proto = out.File
	file_market_service_proto_goTypes = nil
	file_market_service_proto_depIdxs = nil
}
