// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: jobs_service.proto

package jobsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentUserId *uint32                `protobuf:"varint,2,opt,name=current_user_id,json=currentUserId,proto3,oneof" json:"current_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_jobs_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetJobRequest) GetCurrentUserId() uint32 {
	if x != nil && x.CurrentUserId != nil {
		return *x.CurrentUserId
	}
	return 0
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobJson       []byte                 `protobuf:"bytes,1,opt,name=job_json,json=jobJson,proto3" json:"job_json,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_jobs_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobResponse) GetJobJson() []byte {
	if x != nil {
		return x.JobJson
	}
	return nil
}

func (x *GetJobResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	CurrentUserId *uint32                `protobuf:"varint,3,opt,name=current_user_id,json=currentUserId,proto3,oneof" json:"current_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_jobs_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobsRequest) GetCurrentUserId() uint32 {
	if x != nil && x.CurrentUserId != nil {
		return *x.CurrentUserId
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemsJson     []byte                 `protobuf:"bytes,1,opt,name=items_json,json=itemsJson,proto3" json:"items_json,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_jobs_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListJobsResponse) GetItemsJson() []byte {
	if x != nil {
		return x.ItemsJson
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListJobsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadJson   []byte                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_jobs_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateJobRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *CreateJobRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobJson       []byte                 `protobuf:"bytes,1,opt,name=job_json,json=jobJson,proto3" json:"job_json,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobResponse) Reset() {
	*x = CreateJobResponse{}
	mi := &file_jobs_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResponse) ProtoMessage() {}

func (x *CreateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResponse.ProtoReflect.Descriptor instead.
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateJobResponse) GetJobJson() []byte {
	if x != nil {
		return x.JobJson
	}
	return nil
}

func (x *CreateJobResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type UpdateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobRequest) Reset() {
	*x = UpdateJobRequest{}
	mi := &file_jobs_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobRequest) ProtoMessage() {}

func (x *UpdateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateJobRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateJobRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type UpdateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobJson       []byte                 `protobuf:"bytes,1,opt,name=job_json,json=jobJson,proto3" json:"job_json,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobResponse) Reset() {
	*x = UpdateJobResponse{}
	mi := &file_jobs_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobResponse) ProtoMessage() {}

func (x *UpdateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobResponse) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateJobResponse) GetJobJson() []byte {
	if x != nil {
		return x.JobJson
	}
	return nil
}

func (x *UpdateJobResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DeleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobRequest) Reset() {
	*x = DeleteJobRequest{}
	mi := &file_jobs_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobRequest) ProtoMessage() {}

func (x *DeleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteJobRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobResponse) Reset() {
	*x = DeleteJobResponse{}
	mi := &file_jobs_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobResponse) ProtoMessage() {}

func (x *DeleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteJobResponse) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteJobResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type SearchJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	CurrentUserId *uint32                `protobuf:"varint,4,opt,name=current_user_id,json=currentUserId,proto3,oneof" json:"current_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchJobsRequest) Reset() {
	*x = SearchJobsRequest{}
	mi := &file_jobs_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobsRequest) ProtoMessage() {}

func (x *SearchJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobsRequest.ProtoReflect.Descriptor instead.
func (*SearchJobsRequest) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{10}
}

func (x *SearchJobsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchJobsRequest) GetCurrentUserId() uint32 {
	if x != nil && x.CurrentUserId != nil {
		return *x.CurrentUserId
	}
	return 0
}

type SearchJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemsJson     []byte                 `protobuf:"bytes,1,opt,name=items_json,json=itemsJson,proto3" json:"items_json,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchJobsResponse) Reset() {
	*x = SearchJobsResponse{}
	mi := &file_jobs_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobsResponse) ProtoMessage() {}

func (x *SearchJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobsResponse.ProtoReflect.Descriptor instead.
func (*SearchJobsResponse) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{11}
}

func (x *SearchJobsResponse) GetItemsJson() []byte {
	if x != nil {
		return x.ItemsJson
	}
	return nil
}

func (x *SearchJobsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchJobsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type RecordViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint32                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        *uint32                `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	IpAddress     *string                `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3,oneof" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordViewRequest) Reset() {
	*x = RecordViewRequest{}
	mi := &file_jobs_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewRequest) ProtoMessage() {}

func (x *RecordViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewRequest.ProtoReflect.Descriptor instead.
func (*RecordViewRequest) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{12}
}

func (x *RecordViewRequest) GetJobId() uint32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *RecordViewRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *RecordViewRequest) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

type RecordViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordViewResponse) Reset() {
	*x = RecordViewResponse{}
	mi := &file_jobs_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewResponse) ProtoMessage() {}

func (x *RecordViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewResponse.ProtoReflect.Descriptor instead.
func (*RecordViewResponse) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{13}
}

type ListFeedItemsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Limit               int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeTimestampUnix *int64                 `protobuf:"varint,2,opt,name=before_timestamp_unix,json=beforeTimestampUnix,proto3,oneof" json:"before_timestamp_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListFeedItemsRequest) Reset() {
	*x = ListFeedItemsRequest{}
	mi := &file_jobs_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsRequest) ProtoMessage() {}

func (x *ListFeedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedItemsRequest) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListFeedItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFeedItemsRequest) GetBeforeTimestampUnix() int64 {
	if x != nil && x.BeforeTimestampUnix != nil {
		return *x.BeforeTimestampUnix
	}
	return 0
}

type FeedItemMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModuleType    string                 `protobuf:"bytes,2,opt,name=module_type,json=moduleType,proto3" json:"module_type,omitempty"`
	SourceId      uint32                 `protobuf:"varint,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,8,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	UrlPath       string                 `protobuf:"bytes,9,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItemMsg) Reset() {
	*x = FeedItemMsg{}
	mi := &file_jobs_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItemMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItemMsg) ProtoMessage() {}

func (x *FeedItemMsg) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItemMsg.ProtoReflect.Descriptor instead.
func (*FeedItemMsg) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{15}
}

func (x *FeedItemMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedItemMsg) GetModuleType() string {
	if x != nil {
		return x.ModuleType
	}
	return ""
}

func (x *FeedItemMsg) GetSourceId() uint32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *FeedItemMsg) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItemMsg) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *FeedItemMsg) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *FeedItemMsg) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *FeedItemMsg) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *FeedItemMsg) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

type ListFeedItemsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Items                   []*FeedItemMsg         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextBeforeTimestampUnix *int64                 `protobuf:"varint,2,opt,name=next_before_timestamp_unix,json=nextBeforeTimestampUnix,proto3,oneof" json:"next_before_timestamp_unix,omitempty"`
	Error                   *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListFeedItemsResponse) Reset() {
	*x = ListFeedItemsResponse{}
	mi := &file_jobs_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsResponse) ProtoMessage() {}

func (x *ListFeedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedItemsResponse) Descriptor() ([]byte, []int) {
	return file_jobs_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListFeedItemsResponse) GetItems() []*FeedItemMsg {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFeedItemsResponse) GetNextBeforeTimestampUnix() int64 {
	if x != nil && x.NextBeforeTimestampUnix != nil {
		return *x.NextBeforeTimestampUnix
	}
	return 0
}

func (x *ListFeedItemsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_jobs_service_proto protoreflect.FileDescriptor

const file_jobs_service_proto_rawDesc = "" +
	"\n" +
	"\x12jobs_service.proto\x12\ajobs.v1\"`\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12+\n" +
	"\x0fcurrent_user_id\x18\x02 \x01(\rH\x00R\rcurrentUserId\x88\x01\x01B\x12\n" +
	"\x10_current_user_id\"P\n" +
	"\x0eGetJobResponse\x12\x19\n" +
	"\bjob_json\x18\x01 \x01(\fR\ajobJson\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"|\n" +
	"\x0fListJobsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12+\n" +
	"\x0fcurrent_user_id\x18\x03 \x01(\rH\x00R\rcurrentUserId\x88\x01\x01B\x12\n" +
	"\x10_current_user_id\"l\n" +
	"\x10ListJobsResponse\x12\x1d\n" +
	"\n" +
	"items_json\x18\x01 \x01(\fR\titemsJson\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"N\n" +
	"\x10CreateJobRequest\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\fR\vpayloadJson\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"S\n" +
	"\x11CreateJobResponse\x12\x19\n" +
	"\bjob_json\x18\x01 \x01(\fR\ajobJson\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"E\n" +
	"\x10UpdateJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\"S\n" +
	"\x11UpdateJobResponse\x12\x19\n" +
	"\bjob_json\x18\x01 \x01(\fR\ajobJson\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\"\n" +
	"\x10DeleteJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"8\n" +
	"\x11DeleteJobResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x94\x01\n" +
	"\x11SearchJobsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12+\n" +
	"\x0fcurrent_user_id\x18\x04 \x01(\rH\x00R\rcurrentUserId\x88\x01\x01B\x12\n" +
	"\x10_current_user_id\"n\n" +
	"\x12SearchJobsResponse\x12\x1d\n" +
	"\n" +
	"items_json\x18\x01 \x01(\fR\titemsJson\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x87\x01\n" +
	"\x11RecordViewRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\rR\x05jobId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\rH\x00R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tH\x01R\tipAddress\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_ip_address\"\x14\n" +
	"\x12RecordViewResponse\"\x7f\n" +
	"\x14ListFeedItemsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x127\n" +
	"\x15before_timestamp_unix\x18\x02 \x01(\x03H\x00R\x13beforeTimestampUnix\x88\x01\x01B\x18\n" +
	"\x16_before_timestamp_unix\"\x92\x02\n" +
	"\vFeedItemMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmodule_type\x18\x02 \x01(\tR\n" +
	"moduleType\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\rR\bsourceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\b \x01(\x03R\fcommentCount\x12\x19\n" +
	"\burl_path\x18\t \x01(\tR\aurlPath\"\xc9\x01\n" +
	"\x15ListFeedItemsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.jobs.v1.FeedItemMsgR\x05items\x12@\n" +
	"\x1anext_before_timestamp_unix\x18\x02 \x01(\x03H\x00R\x17nextBeforeTimestampUnix\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x01R\x05error\x88\x01\x01B\x1d\n" +
	"\x1b_next_before_timestamp_unixB\b\n" +
	"\x06_errorB5Z3github.com/your-moon/grape-backend/api/proto/jobsv1b\x06proto3"

var (
	file_jobs_service_proto_rawDescOnce sync.Once
	file_jobs_service_proto_rawDescData []byte
)

func file_jobs_service_proto_rawDescGZIP() []byte {
	file_jobs_service_proto_rawDescOnce.Do(func() {
		file_jobs_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobs_service_proto_rawDesc), len(file_jobs_service_proto_rawDesc)))
	})
	return file_jobs_service_proto_rawDescData
}

var file_jobs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_jobs_service_proto_goTypes = []any{
	(*GetJobRequest)(nil),         // 0: jobs.v1.GetJobRequest
	(*GetJobResponse)(nil),        // 1: jobs.v1.GetJobResponse
	(*ListJobsRequest)(nil),       // 2: jobs.v1.ListJobsRequest
	(*ListJobsResponse)(nil),      // 3: jobs.v1.ListJobsResponse
	(*CreateJobRequest)(nil),      // 4: jobs.v1.CreateJobRequest
	(*CreateJobResponse)(nil),     // 5: jobs.v1.CreateJobResponse
	(*UpdateJobRequest)(nil),      // 6: jobs.v1.UpdateJobRequest
	(*UpdateJobResponse)(nil),     // 7: jobs.v1.UpdateJobResponse
	(*DeleteJobRequest)(nil),      // 8: jobs.v1.DeleteJobRequest
	(*DeleteJobResponse)(nil),     // 9: jobs.v1.DeleteJobResponse
	(*SearchJobsRequest)(nil),     // 10: jobs.v1.SearchJobsRequest
	(*SearchJobsResponse)(nil),    // 11: jobs.v1.SearchJobsResponse
	(*RecordViewRequest)(nil),     // 12: jobs.v1.RecordViewRequest
	(*RecordViewResponse)(nil),    // 13: jobs.v1.RecordViewResponse
	(*ListFeedItemsRequest)(nil),  // 14: jobs.v1.ListFeedItemsRequest
	(*FeedItemMsg)(nil),           // 15: jobs.v1.FeedItemMsg
	(*ListFeedItemsResponse)(nil), // 16: jobs.v1.ListFeedItemsResponse
}
var file_jobs_service_proto_depIdxs = []int32{
	15, // 0: jobs.v1.ListFeedItemsResponse.items:type_name -> jobs.v1.FeedItemMsg
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_jobs_service_proto_init() }
func file_jobs_service_proto_init() {
	if File_jobs_service_proto != nil {
		return
	}
	file_jobs_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[14].OneofWrappers = []any{}
	file_jobs_service_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobs_service_proto_rawDesc), len(file_jobs_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobs_service_proto_goTypes,
		DependencyIndexes: file_jobs_service_proto_depIdxs,
		MessageInfos:      file_jobs_service_proto_msgTypes,
	}.Build()
	File_jobs_service_proto = out.File
	file_jobs_service_proto_goTypes = nil
	file_jobs_service_proto_depIdxs = nil
}
